name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B test jacoco:report --file pom.xml

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP of source code
        run: |
          zip -r source-code.zip .
      - name: Create Git tag with date and time
        run: |
          TAG=$(date +'%Y-%m-%d-%H%M%S')  # Tag erstellen
          echo "TAG=$TAG" >> $GITHUB_ENV  # Speichern in Umgebungsvariable
          git tag "$TAG"
          git push origin "$TAG"
      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: source-code.zip
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}